-- Sinh bởi tools/MySqlToSqlServer.java — không sửa tay.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO
BEGIN TRANSACTION;
GO
ALTER TABLE ChuyenTrangThaiHopLe NOCHECK CONSTRAINT ALL;
ALTER TABLE DanhMucNhan NOCHECK CONSTRAINT ALL;
ALTER TABLE QuyenHan NOCHECK CONSTRAINT ALL;
ALTER TABLE TramDichVu NOCHECK CONSTRAINT ALL;
ALTER TABLE VaiTro NOCHECK CONSTRAINT ALL;
ALTER TABLE VaiTro_QuyenHan NOCHECK CONSTRAINT ALL;
GO
INSERT INTO ChuyenTrangThaiHopLe (TuTrangThai, DenTrangThai, MoTa) VALUES
  (N'AWAITING_CUSTOMER_CONFIRMATION', N'AWAITING_PARTS', N'T7a Khách đồng ý'),
  (N'AWAITING_CUSTOMER_CONFIRMATION', N'CANCELLED', N'T7b Khách từ chối'),
  (N'AWAITING_PARTS', N'REPAIRING', N'T9 Duyệt xuất kho / T9c Đủ LK ngoài kho'),
  (N'AWAITING_QUOTE_APPROVAL', N'AWAITING_CUSTOMER_CONFIRMATION', N'T6a Quản lý duyệt báo giá'),
  (N'AWAITING_QUOTE_APPROVAL', N'DIAGNOSED', N'T6b Quản lý yêu cầu sửa lại báo giá'),
  (N'CANCELLED', N'RETURNED_UNREPAIRED', N'T12 Trả máy không sửa'),
  (N'COMPLETED', N'DELIVERED', N'T12 Bàn giao'),
  (N'DIAGNOSED', N'AWAITING_PARTS', N'T8 Yêu cầu xuất LK ca miễn phí'),
  (N'DIAGNOSED', N'AWAITING_QUOTE_APPROVAL', N'T5 Lập báo giá'),
  (N'DIAGNOSED', N'REPAIRING', N'T4 Bắt đầu sửa ca miễn phí không cần LK'),
  (N'INSPECTING', N'DIAGNOSED', N'T3 Lưu kết quả kiểm tra'),
  (N'RECEIVED', N'INSPECTING', N'T2 Phân công KTV'),
  (N'REPAIRING', N'COMPLETED', N'T10 QC đạt');
GO
INSERT INTO DanhMucNhan (Nhom, Ma, NhanNghiepVu, NhanGiaoDien, Tone, ThuTu) VALUES
  (N'ACCESSORIES', N'COMPLETE', N'Đủ', N'Đủ', NULL, 1),
  (N'ACCESSORIES', N'MISSING', N'Thiếu', N'Thiếu', NULL, 2),
  (N'ACCOUNT_STATUS', N'ACTIVE', N'Đang hoạt động', N'Đang hoạt động', N'success', 1),
  (N'ACCOUNT_STATUS', N'LOCKED', N'Đã khóa', N'Đã khóa', N'danger', 2),
  (N'CHANNEL', N'COUNTER', N'Tại quầy', N'Tại quầy', NULL, 1),
  (N'CHANNEL', N'MOBILE_APP', N'Qua App Mobile', N'Qua App Mobile', NULL, 2),
  (N'CHANNEL', N'ONLINE_REQUEST', N'Đăng ký trực tuyến', N'Đăng ký trực tuyến', NULL, 3),
  (N'CHANNEL', N'PHONE', N'Qua điện thoại', N'Qua điện thoại', NULL, 4),
  (N'COSMETIC_MOISTURE', N'NONE', N'Không', N'Không', NULL, 1),
  (N'COSMETIC_MOISTURE', N'SUSPECTED', N'Nghi ngờ', N'Nghi ngờ', NULL, 2),
  (N'COSMETIC_MOISTURE', N'YES', N'Có', N'Có', NULL, 3),
  (N'COSMETIC_SCRATCH', N'HEAVY', N'Nặng', N'Nặng', NULL, 3),
  (N'COSMETIC_SCRATCH', N'LIGHT', N'Nhẹ', N'Nhẹ', NULL, 2),
  (N'COSMETIC_SCRATCH', N'NONE', N'Không', N'Không', NULL, 1),
  (N'CUSTOMER_STATUS', N'ACTIVE', N'Đang hoạt động', N'Đang hoạt động', N'success', 1),
  (N'CUSTOMER_STATUS', N'ARCHIVED', N'Đã lưu trữ', N'Đã lưu trữ', N'neutral', 2),
  (N'CUSTOMER_STATUS', N'MERGED', N'Đã gộp', N'Đã gộp', N'neutral', 3),
  (N'PAYMENT_METHOD', N'BANK_TRANSFER', N'Chuyển khoản', N'Chuyển khoản', NULL, 2),
  (N'PAYMENT_METHOD', N'CARD', N'Thẻ', N'Thẻ', NULL, 4),
  (N'PAYMENT_METHOD', N'CASH', N'Tiền mặt', N'Tiền mặt', NULL, 1),
  (N'PAYMENT_METHOD', N'E_WALLET', N'Ví điện tử', N'Ví điện tử', NULL, 3),
  (N'PAYMENT_METHOD', N'NONE', N'Không áp dụng', N'Không áp dụng', NULL, 5),
  (N'PAYMENT_TYPE', N'CHARGED', N'Thu tiền sửa chữa', N'Đã thanh toán', N'success', 1),
  (N'PAYMENT_TYPE', N'FREE_WARRANTY', N'Miễn phí bảo hành', N'Miễn phí bảo hành', N'success', 2),
  (N'PRIORITY', N'LOW', N'Thấp', N'Thấp', N'neutral', 3),
  (N'PRIORITY', N'NORMAL', N'Bình thường', N'Bình thường', N'neutral', 2),
  (N'PRIORITY', N'URGENT', N'Gấp', N'Gấp', N'danger', 1),
  (N'QC_RESULT', N'FAIL', N'Chưa đạt', N'Không đạt QC', N'danger', 2),
  (N'QC_RESULT', N'PASS', N'Đạt', N'QC đạt', N'success', 1),
  (N'QC_STEP', N'DATA', N'Xác nhận dữ liệu', N'05 Xác nhận dữ liệu', NULL, 5),
  (N'QC_STEP', N'FINAL', N'Kết quả QC', N'06 Kết quả QC', NULL, 6),
  (N'QC_STEP', N'MAIN_FUNCTION', N'Kiểm tra chức năng chính', N'02 Kiểm tra chức năng chính', NULL, 2),
  (N'QC_STEP', N'POWER_CHARGING', N'Kiểm tra nguồn/sạc', N'04 Kiểm tra nguồn/sạc', NULL, 4),
  (N'QC_STEP', N'SECONDARY', N'Kiểm tra phụ', N'03 Kiểm tra phụ', NULL, 3),
  (N'QC_STEP', N'VISUAL', N'Kiểm tra ngoại quan', N'01 Kiểm tra ngoại quan', NULL, 1),
  (N'QUOTE_APPROVAL', N'APPROVED', N'Quản lý đã duyệt', N'Đã phê duyệt', N'success', 2),
  (N'QUOTE_APPROVAL', N'PENDING', N'Chờ duyệt', N'Chờ phê duyệt', N'warning', 1),
  (N'QUOTE_APPROVAL', N'REJECTED', N'Từ chối duyệt', N'Bị từ chối', N'danger', 3),
  (N'QUOTE_CUSTOMER', N'ACCEPTED', N'Đồng ý', N'Đã xác nhận', N'success', 2),
  (N'QUOTE_CUSTOMER', N'DECLINED', N'Từ chối', N'Khách từ chối', N'danger', 3),
  (N'QUOTE_CUSTOMER', N'PENDING', N'Chờ phản hồi', N'Chờ khách xác nhận', N'warning', 1),
  (N'REPAIR_ORDER', N'CANCELLED', N'DaHuy', N'Đã hủy', N'neutral', 4),
  (N'REPAIR_ORDER', N'DONE', N'HoanThanh', N'Hoàn thành', N'success', 3),
  (N'REPAIR_ORDER', N'IN_PROGRESS', N'DangSua', N'Đang sửa', N'processing', 2),
  (N'REPAIR_ORDER', N'PENDING', N'ChoSua', N'Chờ sửa', N'neutral', 1),
  (N'REQUEST_TYPE', N'PAID_REPAIR', N'Sửa chữa dịch vụ', N'Sửa chữa dịch vụ', NULL, 2),
  (N'REQUEST_TYPE', N'WARRANTY', N'Bảo hành', N'Bảo hành', NULL, 1),
  (N'SLA_LEVEL', N'EXPRESS_12H', N'Nhanh (12h)', N'Nhanh (12h)', NULL, 1),
  (N'SLA_LEVEL', N'PRIORITY_24H', N'Ưu tiên (24h)', N'Ưu tiên (24h)', NULL, 2),
  (N'SLA_LEVEL', N'STANDARD_48H', N'Tiêu chuẩn (48h)', N'Tiêu chuẩn (48h)', NULL, 3),
  (N'STEP_RESULT', N'FAIL', N'Không đạt', N'Không đạt', N'danger', 3),
  (N'STEP_RESULT', N'NA', N'Không áp dụng', N'Không áp dụng', N'neutral', 4),
  (N'STEP_RESULT', N'PASS', N'Đạt', N'Đạt', N'success', 2),
  (N'STEP_RESULT', N'PENDING', N'Chưa kiểm tra', N'Chưa kiểm tra', N'neutral', 1),
  (N'STOCK_ISSUE', N'ISSUED', N'DaXuat', N'Đã xuất kho', N'success', 2),
  (N'STOCK_ISSUE', N'PENDING', N'ChoXuat', N'Chờ duyệt', N'warning', 1),
  (N'STOCK_ISSUE', N'REJECTED', N'DaHuy', N'Đã từ chối', N'danger', 3),
  (N'STOCK_RECEIPT', N'APPROVED', N'Đã nhập kho', N'Đã nhập kho', N'success', 2),
  (N'STOCK_RECEIPT', N'PENDING', N'Chờ duyệt', N'Chờ duyệt', N'warning', 1),
  (N'STOCK_RECEIPT', N'REJECTED', N'Đã từ chối', N'Đã từ chối', N'danger', 3),
  (N'STOCK_TRANSFER', N'COMPLETED', N'Đã điều chuyển', N'Đã điều chuyển', N'success', 2),
  (N'STOCK_TRANSFER', N'PENDING', N'Chờ duyệt', N'Chờ duyệt', N'warning', 1),
  (N'STOCK_TRANSFER', N'REJECTED', N'Đã từ chối', N'Đã từ chối', N'danger', 3),
  (N'TICKET_STATUS', N'AWAITING_CUSTOMER_CONFIRMATION', N'Chờ khách xác nhận', N'Chờ khách xác nhận', N'warning', 5),
  (N'TICKET_STATUS', N'AWAITING_PARTS', N'Chờ linh kiện', N'Chờ linh kiện', N'warning', 6),
  (N'TICKET_STATUS', N'AWAITING_QUOTE_APPROVAL', N'Chờ duyệt giá', N'Chờ phê duyệt báo giá', N'warning', 4),
  (N'TICKET_STATUS', N'CANCELLED', N'Đã hủy', N'Ngừng sửa theo yêu cầu khách', N'neutral', 10),
  (N'TICKET_STATUS', N'COMPLETED', N'Hoàn thành', N'Sẵn sàng bàn giao', N'success', 8),
  (N'TICKET_STATUS', N'DELIVERED', N'Đã bàn giao', N'Đã hoàn thành', N'success', 9),
  (N'TICKET_STATUS', N'DIAGNOSED', N'Đã chẩn đoán', N'Đã chẩn đoán', N'processing', 3),
  (N'TICKET_STATUS', N'INSPECTING', N'Đang kiểm tra', N'Đang chẩn đoán', N'processing', 2),
  (N'TICKET_STATUS', N'RECEIVED', N'Đã tiếp nhận', N'Chưa phân công', N'neutral', 1),
  (N'TICKET_STATUS', N'REPAIRING', N'Đang sửa chữa', N'Đang sửa chữa', N'processing', 7),
  (N'TICKET_STATUS', N'RETURNED_UNREPAIRED', N'Đã trả máy (hủy)', N'Đã trả máy (không sửa)', N'neutral', 11),
  (N'WARRANTY_AT_INTAKE', N'IN_WARRANTY', N'Còn bảo hành', N'Còn bảo hành', N'success', 1),
  (N'WARRANTY_AT_INTAKE', N'NOT_ACTIVATED', N'Chưa kích hoạt', N'Chưa kích hoạt', N'neutral', 3),
  (N'WARRANTY_AT_INTAKE', N'OUT_OF_WARRANTY', N'Hết bảo hành', N'Hết bảo hành', N'danger', 2),
  (N'WARRANTY_CLASS', N'FREE_WARRANTY', N'Hợp lệ (Miễn phí)', N'Trong bảo hành', N'success', 1),
  (N'WARRANTY_CLASS', N'OUT_OF_WARRANTY', N'Ngoài bảo hành (Tính phí)', N'Ngoài bảo hành', N'warning', 2),
  (N'WARRANTY_CLASS', N'PARTIAL_WARRANTY', N'Bảo hành một phần', N'Bảo hành một phần', N'warning', 3),
  (N'WARRANTY_REQUEST_STATUS', N'CANCELLED', N'Đã hủy', N'Đã hủy', N'neutral', 3),
  (N'WARRANTY_REQUEST_STATUS', N'CONVERTED', N'Đã tiếp nhận', N'Đã tiếp nhận', N'success', 2),
  (N'WARRANTY_REQUEST_STATUS', N'PENDING_INTAKE', N'Chờ tiếp nhận', N'Chờ tiếp nhận', N'warning', 1);
GO
INSERT INTO QuyenHan (MaQuyen, MoTa) VALUES
  (N'ACCOUNT_MANAGE', N'Quản lý tài khoản & phân quyền'),
  (N'AUDIT_READ', N'Xem nhật ký thao tác'),
  (N'CATALOG_MANAGE', N'Quản lý danh mục'),
  (N'CATALOG_READ', N'Xem danh mục'),
  (N'CUSTOMER_ARCHIVE', N'Lưu trữ / xóa hồ sơ khách'),
  (N'CUSTOMER_ACCOUNT_MANAGE', N'Quản lý tài khoản khách (khóa / mở khóa)'),
  (N'CUSTOMER_CREATE', N'Tạo hồ sơ khách'),
  (N'CUSTOMER_MERGE', N'Hợp nhất hồ sơ khách'),
  (N'CUSTOMER_READ_CONTACT', N'Xem liên hệ khách'),
  (N'CUSTOMER_PASSWORD_RESET', N'Đặt lại mật khẩu tài khoản khách'),
  (N'CUSTOMER_READ_PAYMENTS', N'Xem lịch sử thanh toán của khách'),
  (N'CUSTOMER_UPDATE_CONTACT', N'Sửa liên hệ khách'),
  (N'DEVICE_LOOKUP', N'Tra cứu Serial/IMEI, bảo hành'),
  (N'DEVICE_REGISTER', N'Đăng ký thiết bị'),
  (N'HANDOVER_COMPLETE', N'Hoàn tất bàn giao'),
  (N'INVENTORY_READ', N'Xem tồn kho'),
  (N'INVENTORY_READ_COST', N'Xem giá vốn'),
  (N'PAYMENT_COLLECT', N'Thu tiền / xác nhận miễn phí'),
  (N'PAYMENT_READ', N'Xem thanh toán'),
  (N'PORTAL_SELF', N'Xem phiếu của chính mình'),
  (N'QUOTE_CREATE', N'Lập / sửa báo giá'),
  (N'QUOTE_DECIDE_ON_BEHALF', N'Xác nhận báo giá thay khách tại quầy'),
  (N'QUOTE_DECIDE_OWN', N'Khách tự xác nhận báo giá'),
  (N'QUOTE_REVIEW', N'Duyệt báo giá'),
  (N'REPORT_OPERATIONS', N'Báo cáo vận hành'),
  (N'REPORT_SYSTEM', N'Báo cáo toàn hệ thống (doanh thu...)'),
  (N'STOCK_ISSUE_PROCESS', N'Duyệt / từ chối xuất kho'),
  (N'STOCK_ISSUE_REQUEST', N'Gửi yêu cầu linh kiện'),
  (N'STOCK_RECEIPT_MANAGE', N'Lập / duyệt / từ chối nhập kho'),
  (N'STOCK_TRANSFER_MANAGE', N'Điều chuyển kệ'),
  (N'TICKET_ASSIGN', N'Phân công KTV'),
  (N'TICKET_CREATE', N'Lập phiếu tiếp nhận'),
  (N'TICKET_DIAGNOSE', N'Chẩn đoán, phân loại bảo hành'),
  (N'TICKET_NOTE_CUSTOMER', N'Ghi chú cho khách'),
  (N'TICKET_NOTE_INTERNAL', N'Ghi chú nội bộ'),
  (N'TICKET_READ_ALL', N'Xem mọi phiếu'),
  (N'TICKET_READ_ASSIGNED', N'Xem phiếu được giao'),
  (N'TICKET_READ_WAREHOUSE_VIEW', N'Xem phiếu dạng kho (không thông tin khách)'),
  (N'TICKET_REASSIGN', N'Đổi KTV phụ trách'),
  (N'TICKET_REPAIR', N'Sửa chữa, ghi kết quả QC'),
  (N'WARRANTY_REQUEST_HANDLE', N'Xử lý yêu cầu bảo hành online');
GO
INSERT INTO TramDichVu (MaTram, TenTram, DiaChi, HoatDong) VALUES
  (N'HCM', N'Trạm HCM', N'TP. Hồ Chí Minh', 1);
GO
INSERT INTO VaiTro (MaVaiTro, TenHienThi, TenCuV1, TrangDich, MoTa) VALUES
  (N'ADMIN', N'Quản trị viên', N'Admin', N'pages/admin.html', N'Tài khoản & phân quyền, tài khoản khách, danh mục, báo cáo, nhật ký'),
  (N'CASHIER', N'Thu ngân & Bàn giao', N'ThuNgan', N'pages/cashier.html', N'Thu tiền, xác nhận miễn phí, bàn giao'),
  (N'CUSTOMER', N'Khách hàng', N'KhachHang', N'pages/customer-portal.html', N'Tài khoản tra cứu của khách'),
  (N'DISPATCHER', N'Điều phối viên', N'QuanLy', N'index.html', N'Phân công, duyệt báo giá, quản lý hồ sơ khách'),
  (N'RECEPTIONIST', N'Tiếp nhận & Lễ tân', N'TiepNhan', N'pages/receptionist.html', N'Lập phiếu tiếp nhận, hồ sơ khách, xác nhận thay khách'),
  (N'TECHNICIAN', N'Kỹ thuật viên', N'KyThuatVien', N'pages/technician.html', N'Chẩn đoán, báo giá, yêu cầu linh kiện, sửa chữa, QC'),
  (N'WAREHOUSE_KEEPER', N'Quản lý kho vật tư', N'ThuKho', N'pages/warehouse.html', N'Nhập / xuất / điều chuyển linh kiện');
GO
INSERT INTO VaiTro_QuyenHan (MaVaiTro, MaQuyen) VALUES
  (N'ADMIN', N'ACCOUNT_MANAGE'),
  (N'ADMIN', N'AUDIT_READ'),
  (N'DISPATCHER', N'AUDIT_READ'),
  (N'ADMIN', N'CATALOG_MANAGE'),
  (N'ADMIN', N'CATALOG_READ'),
  (N'CASHIER', N'CATALOG_READ'),
  (N'DISPATCHER', N'CATALOG_READ'),
  (N'RECEPTIONIST', N'CATALOG_READ'),
  (N'TECHNICIAN', N'CATALOG_READ'),
  (N'WAREHOUSE_KEEPER', N'CATALOG_READ'),
  (N'DISPATCHER', N'CUSTOMER_ARCHIVE'),
  (N'ADMIN', N'CUSTOMER_ACCOUNT_MANAGE'),
  (N'ADMIN', N'CUSTOMER_ARCHIVE'),
  (N'DISPATCHER', N'CUSTOMER_CREATE'),
  (N'RECEPTIONIST', N'CUSTOMER_CREATE'),
  (N'DISPATCHER', N'CUSTOMER_MERGE'),
  (N'ADMIN', N'CUSTOMER_MERGE'),
  (N'CASHIER', N'CUSTOMER_READ_CONTACT'),
  (N'ADMIN', N'CUSTOMER_PASSWORD_RESET'),
  (N'RECEPTIONIST', N'CUSTOMER_PASSWORD_RESET'),
  (N'ADMIN', N'CUSTOMER_READ_CONTACT'),
  (N'DISPATCHER', N'CUSTOMER_READ_CONTACT'),
  (N'RECEPTIONIST', N'CUSTOMER_READ_CONTACT'),
  (N'CASHIER', N'CUSTOMER_READ_PAYMENTS'),
  (N'DISPATCHER', N'CUSTOMER_READ_PAYMENTS'),
  (N'DISPATCHER', N'CUSTOMER_UPDATE_CONTACT'),
  (N'ADMIN', N'CUSTOMER_UPDATE_CONTACT'),
  (N'RECEPTIONIST', N'CUSTOMER_UPDATE_CONTACT'),
  (N'DISPATCHER', N'DEVICE_LOOKUP'),
  (N'RECEPTIONIST', N'DEVICE_LOOKUP'),
  (N'DISPATCHER', N'DEVICE_REGISTER'),
  (N'RECEPTIONIST', N'DEVICE_REGISTER'),
  (N'CASHIER', N'HANDOVER_COMPLETE'),
  (N'DISPATCHER', N'HANDOVER_COMPLETE'),
  (N'RECEPTIONIST', N'HANDOVER_COMPLETE'),
  (N'DISPATCHER', N'INVENTORY_READ'),
  (N'TECHNICIAN', N'INVENTORY_READ'),
  (N'WAREHOUSE_KEEPER', N'INVENTORY_READ'),
  (N'DISPATCHER', N'INVENTORY_READ_COST'),
  (N'WAREHOUSE_KEEPER', N'INVENTORY_READ_COST'),
  (N'CASHIER', N'PAYMENT_COLLECT'),
  (N'CASHIER', N'PAYMENT_READ'),
  (N'DISPATCHER', N'PAYMENT_READ'),
  (N'CUSTOMER', N'PORTAL_SELF'),
  (N'TECHNICIAN', N'QUOTE_CREATE'),
  (N'DISPATCHER', N'QUOTE_DECIDE_ON_BEHALF'),
  (N'RECEPTIONIST', N'QUOTE_DECIDE_ON_BEHALF'),
  (N'CUSTOMER', N'QUOTE_DECIDE_OWN'),
  (N'DISPATCHER', N'QUOTE_REVIEW'),
  (N'ADMIN', N'REPORT_OPERATIONS'),
  (N'DISPATCHER', N'REPORT_OPERATIONS'),
  (N'ADMIN', N'REPORT_SYSTEM'),
  (N'WAREHOUSE_KEEPER', N'STOCK_ISSUE_PROCESS'),
  (N'TECHNICIAN', N'STOCK_ISSUE_REQUEST'),
  (N'WAREHOUSE_KEEPER', N'STOCK_ISSUE_REQUEST'),
  (N'WAREHOUSE_KEEPER', N'STOCK_RECEIPT_MANAGE'),
  (N'WAREHOUSE_KEEPER', N'STOCK_TRANSFER_MANAGE'),
  (N'DISPATCHER', N'TICKET_ASSIGN'),
  (N'RECEPTIONIST', N'TICKET_CREATE'),
  (N'TECHNICIAN', N'TICKET_DIAGNOSE'),
  (N'DISPATCHER', N'TICKET_NOTE_CUSTOMER'),
  (N'TECHNICIAN', N'TICKET_NOTE_CUSTOMER'),
  (N'DISPATCHER', N'TICKET_NOTE_INTERNAL'),
  (N'RECEPTIONIST', N'TICKET_NOTE_INTERNAL'),
  (N'TECHNICIAN', N'TICKET_NOTE_INTERNAL'),
  (N'CASHIER', N'TICKET_READ_ALL'),
  (N'DISPATCHER', N'TICKET_READ_ALL'),
  (N'RECEPTIONIST', N'TICKET_READ_ALL'),
  (N'TECHNICIAN', N'TICKET_READ_ASSIGNED'),
  (N'WAREHOUSE_KEEPER', N'TICKET_READ_WAREHOUSE_VIEW'),
  (N'DISPATCHER', N'TICKET_REASSIGN'),
  (N'TECHNICIAN', N'TICKET_REPAIR'),
  (N'DISPATCHER', N'WARRANTY_REQUEST_HANDLE'),
  (N'RECEPTIONIST', N'WARRANTY_REQUEST_HANDLE');
GO
ALTER TABLE ChuyenTrangThaiHopLe WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE DanhMucNhan WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE QuyenHan WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE TramDichVu WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE VaiTro WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE VaiTro_QuyenHan WITH CHECK CHECK CONSTRAINT ALL;
GO
COMMIT;
GO
